ci:
  skip: [pytest]

repos:
  # Bandit - Security vulnerabilities
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -c
          - pyproject.toml

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.2
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
    # Type check library
    - id: pyright-lib
      name: pyright-lib
      entry: uv run pyright term
      language: python
      types: [python]
      files: ^term/.*
      pass_filenames: false
      always_run: true

    # Type check examples
    - id: pyright-examples
      name: pyright-examples
      entry: uv run --extra dev pyright examples
      language: python
      types: [python]
      files: ^examples/.*
      pass_filenames: false
      always_run: true

    # Run tests
    - id: pytest
      name: pytest
      entry: uv run pytest tests
      language: python
      types: [python]
      files: ^tests/.*
      pass_filenames: false
      always_run: true
      additional_dependencies: ["pytest==8.3.4"]

    # Ruff - Format all files
    - id: ruff-format
      name: Run 'ruff format'
      description: "Run 'ruff format' for extremely fast Python formatting"
      entry: uvx ruff format --force-exclude
      language: python
      types_or: [python, pyi]
      exclude: ^tests/.*
      require_serial: true
      additional_dependencies: ["ruff==0.8.1"]

    # Ruff - Lint and autofix changes
    - id: ruff
      name: Run 'ruff' for extremely fast Python linting
      description: "Run 'ruff' for extremely fast Python linting"
      entry: uvx ruff check --force-exclude
      language: python
      types_or: [python, pyi]
      args: [--fix]
      exclude: ^tests/.*
      require_serial: true
      additional_dependencies: ["ruff==0.8.1"]
